name: Reusable esp32-at workflow template

on:
  workflow_call:
    # parameters from upstream workflow
    inputs:
      module_name:
        required: true
        type: string
      artifacts_name:
        required: true
        type: string
    # parameters from upstream inherit
    secrets:
      AT_OTA_TOKEN_WROOM32:
        required: false
      AT_OTA_TOKEN_WROVER32:
        required: false
      AT_OTA_TOKEN_ESP32_PICO_D4:
        required: false
      AT_OTA_TOKEN_ESP32_SOLO_1:
        required: false
      AT_OTA_TOKEN_ESP32_MINI_1:
        required: false

jobs:
  build-template-esp32:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.10'
    - name: Configure prerequisites
      run: |
        # set module information
        silence_mode=1
        silence_sdkconfig=module_config/module_wrover-32/sdkconfig_silence.defaults
        mkdir build
        echo -e "{\"platform\": \"PLATFORM_ESP32\", \"module\": \"${{ inputs.module_name }}\", \"silence\": ${silence_mode}}" > build/module_info.json

        if ${{ inputs.artifacts_name == 'esp32-at-all-function-test-without-bt' }}; then
          echo -e "CONFIG_AT_FS_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_EAP_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_DRIVER_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_WEB_SERVER_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_WS_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_WEB_CAPTIVE_PORTAL_ENABLE=y" >> ${silence_sdkconfig}
          # disable BT
          echo -e "CONFIG_AT_BLE_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_BLE_HID_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_BLUFI_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_BT_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}

          # enlarge partition table
          app0_size=`cat module_config/module_wrover-32/partitions_at.csv | grep ota_0 | awk -F, '{print $5}'`
          app1_size=`cat module_config/module_wrover-32/partitions_at.csv | grep ota_1 | awk -F, '{print $5}'`
          to_set_size=$((app0_size + app1_size))
          sed -i '/ota_1/d' module_config/module_wrover-32/partitions_at.csv
          to_set_hex_size=`printf "0x%x" ${to_set_size}`
          sed -i '/ota_0/s,'"$app0_size"','"$to_set_hex_size"',g' module_config/module_wrover-32/partitions_at.csv
        fi

        if ${{ inputs.artifacts_name == 'esp32-at-all-function-test-just-bt' }}; then
          # enable BT
          echo -e "CONFIG_AT_BT_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_BT_SPP_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_BT_A2DP_COMMAND_SUPPORT=y" >> ${silence_sdkconfig}
          # disable non BT
          echo -e "CONFIG_AT_FS_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_ETHERNET_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_EAP_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_DRIVER_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_WEB_SERVER_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_WEB_CAPTIVE_PORTAL_ENABLE=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_OTA_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_MDNS_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_WPS_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_SMARTCONFIG_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_PING_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_MQTT_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_HTTP_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_AT_SIGNALING_COMMAND_SUPPORT=n" >> ${silence_sdkconfig}
          echo -e "CONFIG_ESP_WIFI_SLP_IRAM_OPT=n" >> ${silence_sdkconfig}

          # enlarge partition table
          app0_size=`cat module_config/module_wrover-32/partitions_at.csv | grep ota_0 | awk -F, '{print $5}'`
          app1_size=`cat module_config/module_wrover-32/partitions_at.csv | grep ota_1 | awk -F, '{print $5}'`
          to_set_size=$((app0_size + app1_size))
          sed -i '/ota_1/d' module_config/module_wrover-32/partitions_at.csv
          to_set_hex_size=`printf "0x%x" ${to_set_size}`
          sed -i '/ota_0/s,'"$app0_size"','"$to_set_hex_size"',g' module_config/module_wrover-32/partitions_at.csv
        fi

        # update esp32 ota token
        cd components/at/private_include
        rm -f at_ota_token.h
        echo -e "#pragma once" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_WROOM32 \"${{ secrets.AT_OTA_TOKEN_WROOM32 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_WROOM32 \"${{ secrets.AT_OTA_TOKEN_WROOM32 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_WROVER32 \"${{ secrets.AT_OTA_TOKEN_WROVER32 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_WROVER32 \"${{ secrets.AT_OTA_TOKEN_WROVER32 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32_PICO_D4 \"${{ secrets.AT_OTA_TOKEN_ESP32_PICO_D4 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32_PICO_D4 \"${{ secrets.AT_OTA_TOKEN_ESP32_PICO_D4 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32_SOLO_1 \"${{ secrets.AT_OTA_TOKEN_ESP32_SOLO_1 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32_SOLO_1 \"${{ secrets.AT_OTA_TOKEN_ESP32_SOLO_1 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_TOKEN_ESP32_MINI_1 \"${{ secrets.AT_OTA_TOKEN_ESP32_MINI_1 }}\"" >> at_ota_token.h
        echo -e "#define CONFIG_ESP_AT_OTA_SSL_TOKEN_ESP32_MINI_1 \"${{ secrets.AT_OTA_TOKEN_ESP32_MINI_1 }}\"" >> at_ota_token.h
        cd -
    - name: Install environment variables
      run: |
        echo "ESP_AT_FIRMWARE_FROM=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" >> "$GITHUB_ENV"
        ./build.py install
    - name: Compile
      run: |
        ./build.py build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ inputs.artifacts_name }}
        path: |
          sdkconfig
          build/*.bin
          build/*.elf
          build/*.map
          build/bootloader/*.bin
          build/partition_table/*.bin
          build/customized_partitions/*
          build/flasher_args.json
          build/download.config
          build/factory/*
